language: node_js
node_js:
- '0.10'
before_install:
- npm install -g jspm@0.16.0-beta
- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
- jspm install
- jspm install --dev
script:
- gulp travis
env:
  global:
  - secure: k71geT/bie+47wXJm2pjxyojPYmS29GArBo6y7AXNI64LpmG5hkYyMKqeihHjlwuIM3LHd43pMkCBoo7rYRPHcqs4Pc3k3j9UIsMp2QNe4oV9ioQ2Uu2CCkLxTbAMVHJFPPZqddVdO9ziKXMe5zyxl83gqJEvPOnQ5auWy3bvsc=
